public class ReturnClassAssignment {
    public string returnStringMethod(string city, string state){
        string homeTown = (city +' '+ state);
        return homeTown;

    }

    public integer Addition(integer x, integer y){
        integer z = x + y;
        return z;

    }

    public integer Addition(integer x,integer y,integer z,integer m){
        integer sumOff = x+y+z+m;
        return sumOff;
    }
}